// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace SideMenuApp
{
    public partial class CatalogViewController : BaseViewController
    {
        private string _bgPortraitIcon = "CatalogBG";
        private string _bgLandscapeIcon = "CatalogLandscapeBG";

        public override void SetBackgroundImage(bool landscape)
        {
            BGImage.Image = UIImage.FromBundle(landscape ? _bgLandscapeIcon : _bgPortraitIcon);
        }

        public CatalogViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
