// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace SideMenuApp
{
    public partial class InfoViewController : BaseViewController
    {
        private string _bgPortraitIcon = "InfoBG";
        private string _bgLandscapeIcon = "InfoLandscapeBG";

        public override void SetBackgroundImage(bool landscape)
        {
            BGImage.Image = UIImage.FromBundle(landscape ? _bgLandscapeIcon : _bgPortraitIcon);
        }

        public InfoViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
