// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace SideMenuApp
{
    public partial class OrdersViewController : BaseViewController
    {
        private string _bgPortraitIcon = "OrderBG";
        private string _bgLandscapeIcon = "OrderLandscapeBG";

        public override void SetBackgroundImage(bool landscape)
        {
            BGImage.Image = UIImage.FromBundle(landscape ? _bgLandscapeIcon : _bgPortraitIcon);
        }

        public OrdersViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
