// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SideMenuApp
{
	public partial class SaleViewController : BaseViewController
	{
		public SaleViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
