// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace SideMenuApp
{
    public partial class SettingsViewController : BaseViewController
    {
        private string _bgPortraitIcon = "SettingsBG";
        private string _bgLandscapeIcon = "SettingsLandscapeBG";

        public override void SetBackgroundImage(bool landscape)
        {
            BGImage.Image = UIImage.FromBundle(landscape ? _bgLandscapeIcon : _bgPortraitIcon);
        }

        public SettingsViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
